pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge Maven'
            url = 'https://maven.minecraftforge.net'
        }
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == 'net.minecraftforge.gradle.forge') {
                useModule group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: requested.version
            }
        }
    }
}

rootProject.name = 'CardboardStereo'
